### ISSUE TITLE
RegExp invalid group error on named group

### ISSUE THREAD

**Issue by OlivierCuyp** [standard/semistandard#236]
Either I'm missing something obvious or this is a bug ...

Adding RegExp with named group produces this error:

```sh
error  Parsing error: Invalid regular expression: /(?<main>.*\s+)(?<remain>[^\s]+)/: Invalid group  null
```

Here is the corresponding code:

```js
const textMatch = text.match(/(?<main>.*\s+)(?<remain>[^\s]+)/);
```

**On SemiStandard Version:** 12.0.1
**On Node Version:** v10.9.0

**Comment by Flet** [comment]
I've updated to `eslint` 5 and the latest standard config. Is this still an issue?

**Comment by voxpelli** [comment]
2.5 years with no additional reports, but with multiple releases which could have fixed it: I'm going to close this as it's likely to no longer be applicable. If it still is applicable, then lets reopen.
