### ISSUE TITLE
WebStorm (and JetBrains IDEs)

### ISSUE THREAD

**Issue by bjufre** [standard/semistandard#241]
Hello,

I'm opening this issue as a question regarding configuration for WebStorm and other JetBrains IDEs.

I find very clear how to set **standardjs** with different editors or IDEs, but in **semistandard** I don't see a section with information regarding JetBrains. Is the basically the same as **standardjs** (natively supported) or do we have to do some tweaks?

Thank you!

**Comment by ks-s-a** [comment]
What was the problem to apply native standardjs and then set "Use semicolon always" in punctuation tab? Works well for my.
