### ISSUE TITLE
Badge link doesn't work

### ISSUE THREAD

**Issue by thorbenw** [standard/semistandard#262]
**What version of this package are you using?**
latest
**What operating system, Node.js, and npm version?**
Win10, >=8.x, >=6.x
**What happened?**
Badge isn't displayed properly in readme, neither in GitHub nor in npmjs
**What did you expect to happen?**
Badge is displayed properly
**Are you willing to submit a pull request to fix this bug?**
No, because this is due to a 403 error when fetching `https://cdn.rawgit.com/standard/semistandard/master/badge.svg` and I don't know how to fix that and also don't have an idea about an alternative link (`https://raw.githubusercontent.com/standard/semistandard/master/badge.svg` didn't work for me either).

Best regards
Thorben

**Comment by Flet** [comment]
`raw.githubusercontent.com` seems to work.

[![js-semistandard-style](https://raw.githubusercontent.com/standard/semistandard/master/badge.svg)](https://github.com/standard/semistandard)

This has been updated. Thanks!
