### ISSUE TITLE
Update standard to version 16.0.3 that disables the rule `Enforce default parameters to be last (default-param-last)`

### ISSUE THREAD

**Issue by sophia-ma** [standard/semistandard#268]
**What happened?**
Standard upgrade needed as there is a problem with rule -> `Enforce default parameters to be last (default-param-last)` that has been fixed in 16.0.3. 

See here https://github.com/standard/standard/issues/1414

CC @VoxPelli

**Comment by tidusjar** [comment]
Would be good if we could get an estimated timeline on this change being published :)

**Comment by voxpelli** [comment]
I have pushed the update to the repo, but I have not yet access to publish to it. Ping @feross @LinusU

**Comment by voxpelli** [comment]
I no have access to publish + I found time to do so. Released in `16.0.1` 🎉
