### ISSUE TITLE
Move semsistandard to standard

### ISSUE THREAD

**Issue by nemanjapetrovic** [standard/semistandard#272]
Hi guys,

is it possible to move the semistandard features to standard package which will help in maintaining problems as you will have only one repo? Maybe to activate semi by some config file or call argument when running standard?

**Comment by voxpelli** [comment]
It is built on `standard-engine` and the ruleset extends the `standard` one, so not much in this project that cause extra maintenance.

**Comment by voxpelli** [comment]
Forgot to say thank you @nemanjapetrovic 🙏 Great with input on how we can improve our maintenance structure, keep it coming!
