### ISSUE TITLE
Parsing error for static class variables

### ISSUE THREAD

**Issue by Steinmetz18** [standard/semistandard#273]
**What version of this package are you using?**
16.0.1 Latest

**What operating system, Node.js, and npm version?**
Windows, node v16.13.1, npm v8.1.2

**What happened?**
Semistandard considers static variables on a class as : "Parsing error: Unexpected token =" 
![parseError](https://user-images.githubusercontent.com/20957905/175180114-66d21a54-6695-46e0-9f7d-eee4dcd97f74.PNG)

**What did you expect to happen?**
In standard there is no Parse error. ES6 should allow static variables on classes.
![noError](https://user-images.githubusercontent.com/20957905/175180125-3e899500-0727-4b92-bf87-cfe9b9fcb97d.PNG)

I can't disable this error with /* eslint-disable */

**Are you willing to submit a pull request to fix this bug?**
Not sure where to look to figure out how/why this is different.

**Comment by voxpelli** [comment]
Working on releasing a new `17.0.0` that will fix this. See #274. Maybe can have it completed today.
